/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videoclubJavi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import videoclubJavi.Usuarios;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author xp
 */
public class VentanaUsuarios extends javax.swing.JFrame {
    int contador=0;
    
    private Statement estado;
    private ResultSet resultadoConsulta;
    private Connection conexion;
    
    HashMap <String,Usuarios>listaUsuarios=new HashMap();
    /**
     * Creates new form VentanaUsuarios
     */
    public VentanaUsuarios() {
        initComponents();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conexion=DriverManager.getConnection("jdbc:mysql://127.0.0.1/videoclub", "root", "");
            estado=conexion.createStatement();
            resultadoConsulta=estado.executeQuery("Select * from usuarios");
            //cargo el resultado de mi query en un hashmap
            while(resultadoConsulta.next()){
                Usuarios u = new Usuarios();
                u.nombre=resultadoConsulta.getString(2);
                u.apellidos=resultadoConsulta.getString(3);
                u.dni=resultadoConsulta.getInt(1);
                u.email=resultadoConsulta.getString(5);
                u.penalizacion=resultadoConsulta.getInt(4);
                
                
                listaUsuarios.put(resultadoConsulta.getString(1), u);
            }
        }catch(Exception e){
            System.out.println("Error");
        }
    }
    private void escribeDatos(){
        //Usuarios u=listaUsuarios.get("5036787");
        Usuarios u=listaUsuarios.get("5036787");
        if(u!=null){
            jLabel1.setText(u.nombre+"     "+u.apellidos);
            /*jTextArea1.setText("Nombre: "+p.nombre+'\n'+"Numero: "+p.id+'\n'+
                    "Evoluciona de: "+evolucionPrevia(p)+
                    parametroEvolucion(p)+'\n'+
                    "Altura: "+p.height+"dm"+'\n'+
                    "Peso: "+p.weight+"hg"+'\n'+
                    "Especie: "+p.species+'\n'+
                    "Habitat: "+p.habitat+'\n'+
                    "% de captura: "+p.capture_rate+"%"+'\n'+
                    "Experiencia base: "+p.base_experience+'\n'+
                    "Felicidad base: "+p.base_happiness+'\n');
        }else{
            jLabel2.setText("No Hay Datos");
            jTextArea1.setText("No Hay Datos");*/
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        escribeDatos();
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
